export {
  HPI_DISCLOSURE_VERSION,
  acknowledgeProviderDisclosure,
  assertHpiRuntimePathsSafe,
  assertHpiSessionTreeSafe,
  createDefaultHpiConfiguration,
  createInteractiveTuiConfigurationFingerprint,
  hpiConfigurationSchema,
  hpiPluginConfigurationSchema,
  loadHpiConfiguration,
  prepareHpiRuntimeDirectories,
  providerDisclosureCategories,
  providerDisclosureRequired,
  resolveHpiPaths,
  saveHpiConfiguration,
  type HpiConfiguration,
  type HpiPaths,
  type HpiPluginConfiguration,
} from "./configuration.js";
export {
  hpiDoctorReportSchema,
  hpiDoctorStatusSchema,
  inspectBundledCoreExtension,
  inspectPiEngineRelease,
  readPiProviderAuthMetadata,
  runHpiDoctor,
  type HpiDoctorReport,
  type HpiDoctorStatus,
  type HpiProductIdentity,
  type PiProviderAuthMetadata,
  type RunHpiDoctorOptions,
} from "./doctor.js";
export {
  HPI_CORE_EXTENSION_ID,
  HPI_CORE_EXTENSION_VERSION,
  createHunterCoreExtension,
  evaluateHunterToolCall,
  evaluateHunterToolCallWithFilesystem,
  type HunterPermissionProfile,
  type HunterToolCall,
  type HunterToolDecision,
  type HunterToolPolicyContext,
} from "./core-extension.js";
export { createPiProbeFixture, removePiProbeFixture, type PiProbeFixture } from "./fixture.js";
export {
  HpiLaunchBlockedError,
  classifyPiProviderDestination,
  createPiLaunchPlan,
  createRawPiLaunchPlan,
  createQuickSessionHeader,
  createQuickSessionProcessObservation,
  disableHpiPlugin,
  inspectHpiPlugins,
  launchPi,
  repositoryDisplayName,
  resolveBundledCoreExtensionPath,
  resolveBundledPiCliPath,
  resolvePiProviderDestination,
  type CreatePiLaunchPlanOptions,
  type CreateRawPiLaunchPlanOptions,
  type HpiLaunchBlockCode,
  type HpiPluginInspection,
  type PiLaunchPlan,
  type PiProviderDestination,
  type PiProviderDestinationDisposition,
} from "./product-launcher.js";
export { LfOnlyNdjsonDecoder } from "./ndjson.js";
export {
  piProviderUsageReasonSchema,
  piProviderUsageSchema,
  type PiProviderUsage,
  type PiProviderUsageReason,
} from "./provider-usage.js";
export {
  QualifiedPiProcessBlockedError,
  createQualifiedPiJsonProcess,
  type QualifiedPiJsonProcessOptions,
} from "./qualified-pi-process.js";
export {
  PiProbeStageError,
  runPiPublicInterfaceProbe,
  type RunPiPublicInterfaceProbeOptions,
} from "./probe.js";
export {
  PiOperationReplayConflictError,
  PiJsonEngineHost,
  Task6PiEngineHost,
  runPiJsonProcess,
  runTask6PiJsonProcess,
  type PiJsonEngineHostOptions,
  type PiProcessRequest,
  type PiProcessResult,
  task6PiProcessResultSchema,
  type Task6PiEngineHostOptions,
  type Task6PiProcessRequest,
  type Task6PiProcessBoundary,
  type Task6PiProcessRunner,
  type Task6PiProcessResult,
} from "./task6-engine-host.js";
export {
  PI_CANDIDATE,
  PI_PROBE_BUILT_EXECUTION_FILES,
  PI_PROBE_SOURCE_FILES,
  PI_PROBE_SOURCE_EXECUTION_FILES,
  derivePiEngineCapabilityResults,
  piCandidateReceiptSchema,
  piProbeFailureStageSchema,
  piProbeImplementationReceiptSchema,
  piProbeStatusSchema,
  piPublicInterfaceProbeFailureReportSchema,
  piPublicInterfaceProbeReportSchema,
  piPublicInterfaceSurfacesSchema,
  type PiCandidateReceipt,
  type PiProbeFailureStage,
  type PiProbeImplementationReceipt,
  type PiProbeStatus,
  type PiPublicInterfaceProbeFailureReport,
  type PiPublicInterfaceProbeReport,
  type PiPublicInterfaceSurfaces,
} from "./schemas.js";
export {
  PI_PACKAGE_INSTALL_WORKER_ARGUMENT,
  type PiPackageInstallWorkerPayload,
} from "./pi-package-install-contract.js";
export { runPiPackageInstallWorkerPayload } from "./pi-package-install-worker.js";
export {
  PiPackageManifestResolver,
  createLocalPiPluginSource,
  createPiPackageInstallWorkerArguments,
  createPiPackageNpmCommand,
  fingerprintNpmRegistryIntegrity,
  fingerprintPiPackageDirectory,
  fingerprintPiPackageResource,
  type PiPackageInspection,
  type PiPackageInstallBudget,
  type PiPackageManifestResolverOptions,
  type PiPackageRuntimeBinding,
  type PiPackageRuntimeResource,
} from "./pi-package-resolver.js";
export {
  FilePiPackageBindingStore,
  piPackageRuntimeBindingReceiptSchema,
  prepareQualifiedPiPluginActivation,
  type PiPluginActivationCompatibilityContext,
  type PiPackageRuntimeBindingReceipt,
  type QualifiedPiPluginActivation,
} from "./plugin-activation.js";
export {
  HpiPluginOperationError,
  hpiPluginOperationError,
  type HpiPluginOperationErrorCode,
} from "./plugin-errors.js";
export {
  PI_PACKAGE_METADATA_VERIFIER_FINGERPRINT,
  fingerprintPiPackageManifest,
  piPackageQualificationReceiptSchema,
  qualifyPiPackageInspection,
  readPiPackageQualificationReceipt,
  type PiPackageQualificationReceipt,
} from "./plugin-qualification.js";
